### ISSUE TITLE
[BUG] java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW         at com.github.benmanes.caffeine.cache.LocalCacheFactory

### ISSUE THREAD

**Issue by acmpo6ou** [eb4j/stardict4j#31]
**Describe the bug**
Hello, thank you for this library! I like it!
I'm trying to write an Android app with it, but when I call `StarDictDictionary.loadDictionary(file)` it throws an exception:
```
java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW
        at com.github.benmanes.caffeine.cache.LocalCacheFactory
...
Caused by: java.lang.Error: java.lang.NoSuchFieldException: No field threadLocalRandomProbe in class Ljava/lang/Thread; (declaration of 'java.lang.Thread' appears in /apex/com.android.art/javalib/core-oj.jar-transformed)
```
I searched the error message, and found [this](https://github.com/ben-manes/caffeine/issues/334).

It seems that you're using the `caffeine` caching library, and it doesn't work on Android. Maybe it's possible to somehow turn off the caching?

**To Reproduce**
`StarDictDictionary.loadDictionary(file)`

**Expected behavior**
dictionary is loaded

**Conditions**
 - OS: Android 12
 - Java: openjdk 11.0.15
 - Version [0.3.0]

**Comment by miurahr** [comment]
Thank you for report and sorry for late response.

**Comment by miurahr** [comment]
@acmpo6ou you can find a new project https://codeberg.org/miurahr/stardict4j-light that is the fork without cache.
You are welcome to join a development as the launch user.

**Comment by acmpo6ou** [comment]
Thank you, I'll check it out!
